fix more

diff --git a/cli/bin/katutil b/cli/bin/katutil
--- a/cli/bin/katutil
+++ b/cli/bin/katutil
@@ -1,15 +1,17 @@
 #!/bin/sh
 EXECUTABLE_PATH=`dirname $0`
 
+log() { echo "$@" 1>&2; }
+
 # if API_ENDPOINT var is not set then use docker to run katutil
 
 if [[ -z "$API_ENDPOINT" ]]; then
   docker inspect katutil &> /dev/null
   if [ $? -ne 0 ]; then
     EXECUTABLE_PATH=`dirname $0`
-    echo $EXECUTABLE_PATH
-    echo "katutil image not found, building ..."
-    docker build -f $EXECUTABLE_PATH/../Dockerfile $EXECUTABLE_PATH/.. -t katutil
+    log $EXECUTABLE_PATH
+    log "katutil image not found, building ..."
+    docker build -f $EXECUTABLE_PATH/../Dockerfile $EXECUTABLE_PATH/../.. -t katutil
   fi
   docker run -i -e API_ENDPOINT=$API_ENDPOINT -e AUTH_ENDPOINT=$AUTH_ENDPOINT -v `pwd`:`pwd` --network="host" --rm katutil "$@"
 else
